const menu = [
  {
    id: 1,
    title: 'Nasi Lemak',
    category: 'breakfast',
    price: 11.99,
    img: 'https://i2.wp.com/www.lokalocal.com/blog/wp-content/uploads/2017/10/1-nasilemak@adventu.rynn-v1.png?resize=1024%2C859&ssl=1',
    desc: `Rice cooked in coconut milk served with hard-boiled egg, peanuts, vegetables, lamb/chicken/beef curry and sambal (chili-based sauce).`,
  },
  {
    id: 2,
    title: 'Kaya Toast with eggs',
    category: 'breakfast',
    price: 6.99,
    img: 'https://burpple.imgix.net/foods/3f08ee7f9759acd63621715289_original.?w=645&dpr=1&fit=crop&q=80&auto=format',
    desc: `Toasted bread served with soft boiled eggs slathered with sweet and fragrant coconut custard jam. Served with coffee. `,
  },
  {
    id: 3,
    title: 'Roti Canai',
    category: 'breakfast',
    price: 9.99,
    img: "https://i.imgur.com/Kd4CJW5.png",
    desc: `Traditional fragrant flatbread served with daal, fish curry and mutton curry.`,
  },
  {
    id: 4,
    title: 'Sliced pork and wonton noodles',
    category: 'breakfast',
    price: 10.99,
    img: 'https://theculturetrip.com/wp-content/uploads/2018/05/shutterstock_389889049.jpg',
    desc: `Springy egg noodles served al dente with a sticky sauce made from soy sauce and lard oil. Served with Chinese kale, sliced green onions, pickled green chilies and steamed wontons.`,
  },
  {
    id: 5,
    title: 'Century Egg Congee',
    category: 'breakfast',
    price: 22.99,
    img: 'https://www.wokandkin.com/wp-content/uploads/2020/02/Century-Egg-and-Pork-Congee-saved-for-web-500x500.png',
    desc: `Hot congee served with century egg slices and long golden-brown deep-fried strips of dough (Youtiao).`,
  },
  {
    id: 6,
    title: 'Stir Fried Noodles (Char Kway Teow)',
    category: 'lunch',
    price: 9.99,
    img: 'https://d2wtgwi3o396m5.cloudfront.net/recipe/844c8140-fc58-42d5-8eff-997aab276bc9.jpeg?d=1408x1120',
    desc: ` flat rice noodles stir fried in dark and light soy sauce, chili, de-shelled cockles, bean sprouts, Chinese chives,prawns and eggs.`,
  },
  {
    id: 7,
    title: 'Laksa',
    category: 'lunch',
    price: 11.99,
    img: 'https://i.imgur.com/YionU0Z.png',
    desc: ` spicy noodle soup  with chicken, prawn or fish, served in spicy soup based on a choice of rich and spicy curry coconut milk or on sour Asam spices. Noodle variations include vermicelli or thick rice noodles. `,
  },
  {
    id: 8,
    title: 'Mee Goreng',
    category: 'lunch',
    price: 11.99,
    img: 'https://recipeguru.org/wp-content/uploads/2020/04/mee-goreng-mamak-recipe-676x320.jpg',
    desc: `Stir fried yellow noodles cooked with beef or chicken, shrimp, soy sauce, veggies and eggs`,
  },
  {
    id: 9,
    title: 'Roti Jala',
    category: 'lunch',
    price: 8.99,
    img: 'https://www.rotinrice.com/wp-content/uploads/2012/03/RotiJala-1.jpg',
    desc: `Crepe like dish served with chicken or beef curry. Also known as "net bread"`,
  },
  {
    id: 10,
    title: 'Roti John',
    category: 'lunch',
    price: 9.99,
    img: 'https://whattocooktoday.com/wp-content/uploads/2020/05/roti-john-19-500x500.jpg',
    desc: `Sandwinch made with grilled minced meat and egg, topped with condiments of choice.`,
  },
  {
    id: 11,
    title: 'Bak Kut Teh (Pork Broth)',
    category: 'dinner',
    price: 11.99,
    img: 'https://www.seriouseats.com/images/20080918-porksoup.jpg',
    desc: 'Broth infused with herbs such as Dong Quai, cinnamon, star anise, and made with pork ribs, with Shitake Mushrooms and garlic.'
  },
  {
    id: 12,
    title: 'Satay',
    category: 'dinner',
    price: 9.99,
    img: 'https://www.thespruceeats.com/thmb/DJY4EU-M-tSv8O2hSHYSsPpSBqk=/2000x1125/smart/filters:no_upscale()/GettyImages-659095647-584859c53df78c023033ffb2.jpg',
    desc: 'Grilled skewers, made with chicken, beef or pork. Served with sweet and spicy peanut sauce',
  },
  {
    id: 13,
    title: 'Chicken Curry',
    category: 'dinner',
    price: 10.99,
    img: 'https://recipesaresimple.com/wp-content/uploads/2013/07/MalaysianChickenCurry-300x199.jpg',
    desc: 'Traditional village chicken curry made with traditional herbs, turmeric, kaffir lime leaves, coconut paste and potatoes ',
  },
  {
    id: 14,
    title: 'Asam Pedas Fish (Tamarand spiced fish)',
    category: 'dinner',
    price: 9.99,
    img: 'https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/24C8D260-834C-4DB2-B3FC-CB48B7370ECD/Derivates/d761c133-58ad-44a5-8628-8ccd27e6af30.jpg',
    desc: 'Fresh water fish steamed along with tamarind sauce, ginger, shrimp paste, garlic, chilies and other herbs.',
  },
  {
    id: 15,
    title: 'Hainanese chicken rice',
    category: 'dinner',
    price: 10.99,
    img: 'https://www.seriouseats.com/images/2011/08/20110805-robyn-hainanese.jpg',
    desc: `poached chicken and seasoned rice, served with chili sauce and cucumber garnishes. Originated from Hainan, China`,
  },
  {
    id: 16,
    title: 'Tandoori Chicken',
    category: 'dinner',
    price: 10.99,
    img: 'https://www.cubesnjuliennes.com/wp-content/uploads/2019/11/Tandoori-Chicken-1.jpg',
    desc: `Roasted chicken marinated in yogurt and spices and served with fragrant naan`,
  },
];
export default menu;